package com.imperialm.imiservices.dao;

import java.util.List;

import com.imperialm.imiservices.dto.SIRewardsDetailsDTO;

public interface SIRewardsDetailsDAO {
	//public static String SELECT_BY_DEALER_CODE = "SELECT [DealerCode] 'dealerCode' ,[DealerName] 'dealerName' ,[SID] 'sID' ,[Name] 'name' ,[Toggle] 'toggle' ,[EligibleSurveys] 'eligibleSurveys' ,[IncentiveQualified] 'incentiveQualified' ,[SurveyScore] 'surveyScore' ,[ProjectedEarnings] 'projectedEarnings' ,[level0] 'level0' ,[level1] 'level1' ,[TotalSurveys] 'totalSurveys' ,[BCAdvisorRankEarnings] 'bCAdvisorRankEarnings', [trainingQualified] 'trainingQualified', [DealerTarget] 'dealerTarget', [PositionCode] 'positionCode', [ReportQuarter] 'reportQuarter', [AdvisorSurveys] 'advisorSurveys' FROM [dbo].[SIRewardsDetails] where DealerCode = ?0";
	public static String SELECT_BY_DEALER_CODE_AND_TOGGLE = "SELECT [DealerCode] 'dealerCode' ,[DealerName] 'dealerName' ,[SID] 'sID' ,[Name] 'name' ,[Toggle] 'toggle' ,[EligibleSurveys] 'eligibleSurveys' ,[IncentiveQualified] 'incentiveQualified' ,[SurveyScore] 'surveyScore' ,[ProjectedEarnings] 'projectedEarnings' ,[level0] 'level0' ,[level1] 'level1' ,[TotalSurveys] 'totalSurveys' ,[BCAdvisorRankEarnings] 'bCAdvisorRankEarnings', [trainingQualified] 'trainingQualified', [DealerTarget] 'dealerTarget', [PositionCode] 'positionCode', [ReportQuarter] 'reportQuarter', [AdvisorSurveys] 'advisorSurveys' FROM [dbo].[SIRewardsDetails] where DealerCode = ?0 AND [Toggle] = ?1 AND [ReportQuarter] = ?2";
	public static String SELECT_BY_DEALER_CODE_AND_TOGGLE_AND_POSITIONCODE = "SELECT [DealerCode] 'dealerCode' ,[DealerName] 'dealerName' ,[SID] 'sID' ,[Name] 'name' ,[Toggle] 'toggle' ,[EligibleSurveys] 'eligibleSurveys' ,[IncentiveQualified] 'incentiveQualified' ,[SurveyScore] 'surveyScore' ,[ProjectedEarnings] 'projectedEarnings' ,[level0] 'level0' ,[level1] 'level1' ,[TotalSurveys] 'totalSurveys' ,[BCAdvisorRankEarnings] 'bCAdvisorRankEarnings', [trainingQualified] 'trainingQualified', [DealerTarget] 'dealerTarget', [PositionCode] 'positionCode', [ReportQuarter] 'reportQuarter', [AdvisorSurveys] 'advisorSurveys' FROM [dbo].[SIRewardsDetails] where DealerCode = ?0 AND [Toggle] = ?1 AND [ReportQuarter] = ?2 AND [PositionCode] = ?3";
	public static String SELECT_BY_DEALER_CODE_AND_TOGGLE_AND_POSITIONCODE_LIST = "SELECT [DealerCode] 'dealerCode' ,[DealerName] 'dealerName' ,[SID] 'sID' ,[Name] 'name' ,[Toggle] 'toggle' ,[EligibleSurveys] 'eligibleSurveys' ,[IncentiveQualified] 'incentiveQualified' ,[SurveyScore] 'surveyScore' ,[ProjectedEarnings] 'projectedEarnings' ,[level0] 'level0' ,[level1] 'level1' ,[TotalSurveys] 'totalSurveys' ,[BCAdvisorRankEarnings] 'bCAdvisorRankEarnings', [trainingQualified] 'trainingQualified', [DealerTarget] 'dealerTarget', [PositionCode] 'positionCode', [ReportQuarter] 'reportQuarter', [AdvisorSurveys] 'advisorSurveys' FROM [dbo].[SIRewardsDetails] where DealerCode = ?0 AND [Toggle] = ?1 AND [ReportQuarter] = ?2 AND [PositionCode] IN (?3)";
	public static String SELECT_BY_DEALER_CODE_LIST_AND_TOGGLE_AND_POSITIONCODE_LIST = "SELECT [DealerCode] 'dealerCode' ,[DealerName] 'dealerName' ,[SID] 'sID' ,[Name] 'name' ,[Toggle] 'toggle' ,[EligibleSurveys] 'eligibleSurveys' ,[IncentiveQualified] 'incentiveQualified' ,[SurveyScore] 'surveyScore' ,[ProjectedEarnings] 'projectedEarnings' ,[level0] 'level0' ,[level1] 'level1' ,[TotalSurveys] 'totalSurveys' ,[BCAdvisorRankEarnings] 'bCAdvisorRankEarnings', [trainingQualified] 'trainingQualified', [DealerTarget] 'dealerTarget', [PositionCode] 'positionCode', [ReportQuarter] 'reportQuarter', [AdvisorSurveys] 'advisorSurveys' FROM [dbo].[SIRewardsDetails] where DealerCode IN (?0) AND [Toggle] = ?1 AND [ReportQuarter] = ?2 AND [PositionCode] IN (?3)";
	public static String SELECT_BY_SID = "SELECT [DealerCode] 'dealerCode' ,[DealerName] 'dealerName' ,[SID] 'sID' ,[Name] 'name' ,[Toggle] 'toggle' ,[EligibleSurveys] 'eligibleSurveys' ,[IncentiveQualified] 'incentiveQualified' ,[SurveyScore] 'surveyScore' ,[ProjectedEarnings] 'projectedEarnings' ,[level0] 'level0' ,[level1] 'level1' ,[TotalSurveys] 'totalSurveys' ,[BCAdvisorRankEarnings] 'bCAdvisorRankEarnings', [trainingQualified] 'trainingQualified', [DealerTarget] 'dealerTarget', [PositionCode] 'positionCode', [ReportQuarter] 'reportQuarter', [AdvisorSurveys] 'advisorSurveys' FROM [dbo].[SIRewardsDetails] where [SID] = ?0 AND [DealerCode] = ?1 AND [ReportQuarter] = ?2";
	public static String SELECT_BY_SID_AND_TOGGLE = "SELECT [DealerCode] 'dealerCode' ,[DealerName] 'dealerName' ,[SID] 'sID' ,[Name] 'name' ,[Toggle] 'toggle' ,[EligibleSurveys] 'eligibleSurveys' ,[IncentiveQualified] 'incentiveQualified' ,[SurveyScore] 'surveyScore' ,[ProjectedEarnings] 'projectedEarnings' ,[level0] 'level0' ,[level1] 'level1' ,[TotalSurveys] 'totalSurveys' ,[BCAdvisorRankEarnings] 'bCAdvisorRankEarnings', [trainingQualified] 'trainingQualified', [DealerTarget] 'dealerTarget', [PositionCode] 'positionCode', [ReportQuarter] 'reportQuarter', [AdvisorSurveys] 'advisorSurveys' FROM [dbo].[SIRewardsDetails] where [SID] = ?0 AND [Toggle] = ?1 AND [DealerCode] = ?2 AND [ReportQuarter] = ?3";
	//public List<SIRewardsDetailsDTO> getSIRewardsDetailsByDealerCode(String dealerCode);
	public List<SIRewardsDetailsDTO> getSIRewardsDetailsBySID(String sID, String dealerCode, String quarter);
	public List<SIRewardsDetailsDTO> getSIRewardsDetailsByDealerCodeAndToggle(String dealerCode, String toggle, String quarter);
	public List<SIRewardsDetailsDTO> getSIRewardsDetailsByDealerCodeAndToggleAndPositionCode(String dealerCode, String toggle, String quarter, String positionCode);
	public List<SIRewardsDetailsDTO> getSIRewardsDetailsByDealerCodeAndToggleAndPositionCode(String dealerCode, String toggle, String quarter, List<String> positionCode);
	public List<SIRewardsDetailsDTO> getSIRewardsDetailsByDealerCodeAndToggleAndPositionCode(List<String> dealerCode, String toggle, String quarter, List<String> positionCode);
	public List<SIRewardsDetailsDTO> getSIRewardsDetailsBySIDAndToggle(String sID, String toggle, String dealerCode, String quarter);
	
}
